<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="box_bot">

    <xacro:property name="base_mass"   value="0.8"/>
    <xacro:property name="base_size"   value="0.1"/>
    <xacro:property name="ground_clearance" value="0.01"/>

    <xacro:property name="wheel_mass"  value="0.05"/>
    <xacro:property name="wheel_radius" value="0.035"/>
    <xacro:property name="wheel_length" value="0.01"/>
    <xacro:property name="wheel_ygap"   value="0.05"/>

    <xacro:property name="caster_mass"   value="0.01"/>
    <xacro:property name="caster_radius" value="0.01"/>
    <xacro:property name="caster_xgap"   value="0.035"/>

    <xacro:include filename="box_bot3.gazebo.xacro" /> 
    <xacro:include filename="$(find realsense2_description)/urdf/_d435i.urdf.xacro" />

    <material name="red"><color rgba="1.0 0.0 0.0 1"/></material>
    <material name="green_dark"><color rgba="0.0 0.5 0.0 1"/></material>
    <material name="black"><color rgba="0.0 0.0 0.0 1"/></material>
    <material name="orange"><color rgba="1.0 0.5 0.0 1.0"/></material>
    <material name="blue"><color rgba="0.088656 0.428691 0.491021 1"/></material>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="package://boxbot_description/meshes/cute_cube.dae" scale="0.1 0.1 0.1"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${base_size} ${base_size} ${base_size}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${base_mass}"/>
            <origin rpy="0 0 0" xyz="0 0 -0.02"/>
            <inertia ixx="0.001333" ixy="0" ixz="0" iyy="0.001333" iyz="0" izz="0.001333"/>
        </inertial>
    </link>

    <joint name="base_link_joint" type="fixed">
        <origin xyz="0 0 ${ground_clearance + (base_size/2)}" rpy="0 0 0"/>
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <xacro:sensor_d435i parent="base_link" name="camera" use_nominal_extrinsics="true">
    <origin xyz="0.06 0 0.025" rpy="0 -0.2 0"/>
    </xacro:sensor_d435i>

    <xacro:macro name="wheel" params="prefix side color">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 ${side * 0.005} 0" rpy="0 1.5707 1.5707"/>
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 ${side * 0.005} 0" rpy="0 1.5707 1.5707"/>
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 ${side * 0.005} 0" rpy="0 1.5707 1.5707"/>
                <mass value="${wheel_mass}"/>
                <inertia ixx="1.5316e-05" ixy="0" ixz="0" iyy="1.5316e-05" iyz="0" izz="3.0625e-05"/>
            </inertial>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="0 ${side * wheel_ygap} -0.025" rpy="0 0 0" />
            <child link="${prefix}_wheel_link"/>
            <parent link="base_link"/>
            <axis xyz="0 1 0"/>
            <limit effort="10.0" velocity="10.0"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <gazebo reference="${prefix}_wheel_link">
            <kp>1000000.0</kp>
            <kd>10.0</kd>
            <mu1>10.0</mu1>
            <mu2>10.0</mu2>
            <fdir1>1 0 0</fdir1>
            <material>Gazebo/${color}</material>
        </gazebo>
    </xacro:macro>

    <xacro:wheel prefix="left"  side="1"  color="Green"/>
    <xacro:wheel prefix="right" side="-1" color="Green"/>

    <xacro:macro name="caster" params="prefix x_pos">
        <link name="${prefix}_caster_link">
            <visual>
                <geometry><sphere radius="${caster_radius}"/></geometry>
                <material name="green_dark"/>
            </visual>
            <collision>
                <geometry><sphere radius="${caster_radius}"/></geometry>
            </collision>
            <inertial>
                <mass value="${caster_mass}"/>
                <inertia ixx="4e-07" ixy="0" ixz="0" iyy="4e-07" iyz="0" izz="4e-07"/>
            </inertial>
        </link>

        <joint name="${prefix}_caster_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_caster_link"/>
            <origin xyz="${x_pos} 0 -0.05" rpy="0 0 0"/>
        </joint>

        <gazebo reference="${prefix}_caster_link">
            <mu1>0.01</mu1>
            <mu2>0.01</mu2>
            <material>Gazebo/Purple</material>
        </gazebo>
    </xacro:macro>

    <xacro:caster prefix="front" x_pos="${caster_xgap}"/>
    <xacro:caster prefix="back"  x_pos="${-caster_xgap}"/>

    <!-- Laser Position Control -->
    <link name="laser_scan_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://boxbot_description/meshes/sensors/rplidar.dae" scale="1.0 1.0 1.0"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.0204" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.0408" radius="0.037493"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0.0204" rpy="0 0 0"/>
            <inertia ixx="6.066578520833334e-06" ixy="0" ixz="0" iyy="6.072950163333333e-06" iyz="0" izz="9.365128684166666e-06"/>
        </inertial>
    </link>

    <!-- <joint name="laser_scan_link_joint" type="continuous"> -->
    <joint name="laser_scan_link_joint" type="fixed"> 
        <origin rpy="0 0 0" xyz="0 0 0.05"/>
        <parent link="base_link"/>
        <child link="laser_scan_link"/>    
        <!-- <axis xyz="0 0 1"/>
        <limit effort="10.0" velocity="100.0"/>
        <dynamics damping="0.01" friction="0.01"/> -->
    </joint>

    <!-- IMU -->
    <link name="imu_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.015 0.015 0.0025"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <joint name="imu_joint" type="fixed">
        <origin xyz="0.037 0.037 0.051" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>



    </robot>