<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo reference="camera_link">
        <sensor name="camera" type="depth">
            <visualize>true</visualize>
            <update_rate>30.0</update_rate>
            <camera name="camera">
                <horizontal_fov>1.5184</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>10.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <ros>
                    <!-- <namespace>camera</namespace> -->
                    <remapping>camera/image_raw:=color/image_raw</remapping>
                    <remapping>camera/depth/image_raw:=depth/image_rect_raw</remapping>
                    <remapping>camera/camera_info:=color/camera_info</remapping>
                    <remapping>camera/depth/camera_info:=depth/camera_info</remapping>
                    <remapping>camera/points:=depth/color/points</remapping>
                </ros>
                <camera_name>d435i</camera_name>
                <frame_name>camera_depth_optical_frame</frame_name> <hack_baseline>0.07</hack_baseline>
                <min_depth>0.1</min_depth>
                <max_depth>5.0</max_depth>
            </plugin>
        </sensor>
    </gazebo>

    <gazebo>
        <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
            <ros>
                <remapping>~/out:=joint_states</remapping>
            </ros>
            <update_rate>30</update_rate>
            <joint_name>left_wheel_joint</joint_name>
            <joint_name>right_wheel_joint</joint_name>
            <joint_name>laser_scan_link_joint</joint_name>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>${wheel_ygap * 2}</wheel_separation>
            <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

            <max_wheel_torque>1.0</max_wheel_torque>
            <max_wheel_acceleration>2.0</max_wheel_acceleration>

            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>

            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin>
    </gazebo>

    <gazebo reference="imu_link">
        <sensor name="br_imu" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <imu>
                <angular_velocity>
                    <x><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></x>
                    <y><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></y>
                    <z><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></z>
                </angular_velocity>
                <linear_acceleration>
                    <x><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></x>
                    <y><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></y>
                    <z><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></z>
                </linear_acceleration>
            </imu>
            <plugin name="bytes_imu" filename="libgazebo_ros_imu_sensor.so">
                <ros>
                    <namespace>imu</namespace>
                    <remapping>~/out:=data</remapping>
                </ros>
                <initial_orientation_as_reference>false</initial_orientation_as_reference>
            </plugin>
        </sensor>
    </gazebo>

    <gazebo reference="laser_scan_link">
        <sensor name="lidar" type="ray">
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1.0</resolution>
                        <min_angle>0.00</min_angle>
                        <max_angle>6.28</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.12</min>
                    <max>12.0</max>
                    <resolution>0.015</resolution>
                </range>
            </ray>
            <plugin name="scan_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_scan_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>